/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasesNewRouteImport } from './routes/cases.new'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as CasesCaseIdIndexRouteImport } from './routes/cases.$caseId.index'
import { Route as CasesCaseIdUploadRouteImport } from './routes/cases.$caseId.upload'
import { Route as CasesCaseIdReportRouteImport } from './routes/cases.$caseId.report'
import { Route as CasesCaseIdDecisionRouteImport } from './routes/cases.$caseId.decision'
import { Route as CasesCaseIdAnalyzingRouteImport } from './routes/cases.$caseId.analyzing'
import { Route as CasesCaseIdDocumentDocIdRouteImport } from './routes/cases.$caseId.document.$docId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesNewRoute = CasesNewRouteImport.update({
  id: '/cases/new',
  path: '/cases/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCaseIdIndexRoute = CasesCaseIdIndexRouteImport.update({
  id: '/cases/$caseId/',
  path: '/cases/$caseId/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCaseIdUploadRoute = CasesCaseIdUploadRouteImport.update({
  id: '/cases/$caseId/upload',
  path: '/cases/$caseId/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCaseIdReportRoute = CasesCaseIdReportRouteImport.update({
  id: '/cases/$caseId/report',
  path: '/cases/$caseId/report',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCaseIdDecisionRoute = CasesCaseIdDecisionRouteImport.update({
  id: '/cases/$caseId/decision',
  path: '/cases/$caseId/decision',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCaseIdAnalyzingRoute = CasesCaseIdAnalyzingRouteImport.update({
  id: '/cases/$caseId/analyzing',
  path: '/cases/$caseId/analyzing',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCaseIdDocumentDocIdRoute =
  CasesCaseIdDocumentDocIdRouteImport.update({
    id: '/cases/$caseId/document/$docId',
    path: '/cases/$caseId/document/$docId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/cases/new': typeof CasesNewRoute
  '/cases/$caseId/analyzing': typeof CasesCaseIdAnalyzingRoute
  '/cases/$caseId/decision': typeof CasesCaseIdDecisionRoute
  '/cases/$caseId/report': typeof CasesCaseIdReportRoute
  '/cases/$caseId/upload': typeof CasesCaseIdUploadRoute
  '/cases/$caseId/': typeof CasesCaseIdIndexRoute
  '/cases/$caseId/document/$docId': typeof CasesCaseIdDocumentDocIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/cases/new': typeof CasesNewRoute
  '/cases/$caseId/analyzing': typeof CasesCaseIdAnalyzingRoute
  '/cases/$caseId/decision': typeof CasesCaseIdDecisionRoute
  '/cases/$caseId/report': typeof CasesCaseIdReportRoute
  '/cases/$caseId/upload': typeof CasesCaseIdUploadRoute
  '/cases/$caseId': typeof CasesCaseIdIndexRoute
  '/cases/$caseId/document/$docId': typeof CasesCaseIdDocumentDocIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/cases/new': typeof CasesNewRoute
  '/cases/$caseId/analyzing': typeof CasesCaseIdAnalyzingRoute
  '/cases/$caseId/decision': typeof CasesCaseIdDecisionRoute
  '/cases/$caseId/report': typeof CasesCaseIdReportRoute
  '/cases/$caseId/upload': typeof CasesCaseIdUploadRoute
  '/cases/$caseId/': typeof CasesCaseIdIndexRoute
  '/cases/$caseId/document/$docId': typeof CasesCaseIdDocumentDocIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/dashboard'
    | '/settings'
    | '/admin/users'
    | '/cases/new'
    | '/cases/$caseId/analyzing'
    | '/cases/$caseId/decision'
    | '/cases/$caseId/report'
    | '/cases/$caseId/upload'
    | '/cases/$caseId/'
    | '/cases/$caseId/document/$docId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/dashboard'
    | '/settings'
    | '/admin/users'
    | '/cases/new'
    | '/cases/$caseId/analyzing'
    | '/cases/$caseId/decision'
    | '/cases/$caseId/report'
    | '/cases/$caseId/upload'
    | '/cases/$caseId'
    | '/cases/$caseId/document/$docId'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/dashboard'
    | '/settings'
    | '/admin/users'
    | '/cases/new'
    | '/cases/$caseId/analyzing'
    | '/cases/$caseId/decision'
    | '/cases/$caseId/report'
    | '/cases/$caseId/upload'
    | '/cases/$caseId/'
    | '/cases/$caseId/document/$docId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  DashboardRoute: typeof DashboardRoute
  SettingsRoute: typeof SettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  CasesNewRoute: typeof CasesNewRoute
  CasesCaseIdAnalyzingRoute: typeof CasesCaseIdAnalyzingRoute
  CasesCaseIdDecisionRoute: typeof CasesCaseIdDecisionRoute
  CasesCaseIdReportRoute: typeof CasesCaseIdReportRoute
  CasesCaseIdUploadRoute: typeof CasesCaseIdUploadRoute
  CasesCaseIdIndexRoute: typeof CasesCaseIdIndexRoute
  CasesCaseIdDocumentDocIdRoute: typeof CasesCaseIdDocumentDocIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/new': {
      id: '/cases/new'
      path: '/cases/new'
      fullPath: '/cases/new'
      preLoaderRoute: typeof CasesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$caseId/': {
      id: '/cases/$caseId/'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId/'
      preLoaderRoute: typeof CasesCaseIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$caseId/upload': {
      id: '/cases/$caseId/upload'
      path: '/cases/$caseId/upload'
      fullPath: '/cases/$caseId/upload'
      preLoaderRoute: typeof CasesCaseIdUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$caseId/report': {
      id: '/cases/$caseId/report'
      path: '/cases/$caseId/report'
      fullPath: '/cases/$caseId/report'
      preLoaderRoute: typeof CasesCaseIdReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$caseId/decision': {
      id: '/cases/$caseId/decision'
      path: '/cases/$caseId/decision'
      fullPath: '/cases/$caseId/decision'
      preLoaderRoute: typeof CasesCaseIdDecisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$caseId/analyzing': {
      id: '/cases/$caseId/analyzing'
      path: '/cases/$caseId/analyzing'
      fullPath: '/cases/$caseId/analyzing'
      preLoaderRoute: typeof CasesCaseIdAnalyzingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$caseId/document/$docId': {
      id: '/cases/$caseId/document/$docId'
      path: '/cases/$caseId/document/$docId'
      fullPath: '/cases/$caseId/document/$docId'
      preLoaderRoute: typeof CasesCaseIdDocumentDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  DashboardRoute: DashboardRoute,
  SettingsRoute: SettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  CasesNewRoute: CasesNewRoute,
  CasesCaseIdAnalyzingRoute: CasesCaseIdAnalyzingRoute,
  CasesCaseIdDecisionRoute: CasesCaseIdDecisionRoute,
  CasesCaseIdReportRoute: CasesCaseIdReportRoute,
  CasesCaseIdUploadRoute: CasesCaseIdUploadRoute,
  CasesCaseIdIndexRoute: CasesCaseIdIndexRoute,
  CasesCaseIdDocumentDocIdRoute: CasesCaseIdDocumentDocIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
